### ISSUE TITLE
AC/AN INFO fields in VCF are inconsistent with GT field, update the values in the VCF in chunk 000 and 022

### ISSUE THREAD

**Issue by mookiDu** [srubinacci/imputation-ukb-ref-panel#1]
Hi Simone, 
I'm trying to set up your uk-biobank-imputation-pipelines/low-coverage-pipeline on Dnanexus in the US. I’m pulling the genetic map from here: https://github.com/odelaneau/GLIMPSE/tree/master/maps/genetic_maps.b38 since I do not have access to resources on RAP and the phased vcfs from here: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased and then I remove multiallelic records. Everything for step 2 ( in https://srubinacci.gitbook.io/uk-biobank-imputation-pipelines/low-coverage-pipeline/running-the-low-coverage-pipeline 'First-time usage - Binary reference panel representation') went smoothly for autosomes but for chr X, 2 of the chunks convert_ref_chrX_000 and convert_ref_chrX_022, are failing with the exact error in this discussion https://github.com/odelaneau/GLIMPSE/issues/189. Maybe it is related to the chrX imputation and splitting chromosomes into PAR and notPAR regions and if so I can’t seem to locate the bam file with the non-PAR chr X reads downsampled to 1x. The link in the https://odelaneau.github.io/GLIMPSE/glimpse1/tutorial_chrX.html that says “The data and the scripts for this tutorial can be downloaded [HERE](https://urldefense.com/v3/__https:/drive.switch.ch/index.php/s/9HEdWR1T8ouRTfW__;!!BS-MXwIi!B1_cC5MTEPyajwtcgVB-6o5_9bbaN1m4lJT37lYwEBO6y7Fe7mdYIiqz2EizTuQzNCad6YyObejaq575LU7KW4w$)” is broken and the git page tutorial doesn’t seem to have that bam. I also downloaded Glimpse 2 and 1 and the tutorials there are the same as on the git page. Any ideas where I could locate tutorial_chrX?
Also, how would I call the merged vcf generated in 3.3 with glimpse_split_reference? In the tutorial link the merged vcf from step 3.3 is called with --input parameter for glimps_phase (probably --input-gl in version 2) and ref from step 2 as reference. The split_reference doesn’t have a –input option. Just call it as reference? 
Also, thinking that the pipeline must have been tested successfully for chr x with the resources made available on RAP- I wonder if we could get the splitVCFs hosted there. That might be the quickest resolution.

**Comment by srubinacci** [comment]
Hi,

You can find the GLIMPSE2 tutorial here: 
https://www.dropbox.com/scl/fi/6faka9xfpvwrklgreqp68/tutorial_chrX.tar.gz?rlkey=vlmccthxi0n65ki3g9b2rr09r&dl=0

You might need to split PAR1/nonPAR/PAR2 depending on the reference panel. Basically the program does not want to have a sample changing ploidy in the region. 

Split reference will give you a binary representation of the reference panel to refer in GLIMPSE2_phase as --reference. You do not have to merge these files, keep them separated. 
Then you will need to supply genotype likelihoods (--input-gl) or a set of bams/crams (--bam-list or --bam-file) for the specific region you want to impute.

The UKB phased data has been phased with SHAPEIT5, and it's fully diploid even at chromosome X for males.

Hope it helps,

Simone
